### ISSUE TITLE
Adding my content to Genodian

### ISSUE THREAD

**Issue by acharya-sagar** [genodelabs/genodians.org#28]
Hello fellow Genodians,

I'd like to join Genode and have written my 1st content [here](https://notabug.org/sagaracharya/genodian) .

Thanks
Sagar

**Comment by skalk** [comment]
@acharya-sagar welcome to the Genode community. We'd love to add your repository to genodians.org.
Just a minor request: Would it be possible to use another author's picture in your repository? Of course, you do not have to use a picture of yours. But it would be nice if you could use a plain image no text in a non-ascii encoding. The problem is otherwise few people (including us who host the genodians.org) are not able to parse and translate its semantic. I'm pretty sure that the content is cool and not harmful, but as we are responsible for the aggregation shown on genodians.org, we would like to be able to at least parse and translate it. I hope you understand that. Thank you very much for contributing.

**Comment by acharya-sagar** [comment]
Thanks skalk for the welcome. :)

Is it alright if I update my picture in my next commit? Regarding semantic, it's nothing but my name "Sagar" written in Devanagari, a script which is used in Hindi, a language common in India. I don't want to keep another alias picture except me or my name.

**Comment by skalk** [comment]
> Is it alright if I update my picture in my next commit? Regarding semantic, it's nothing but my name "Sagar" written in Devanagari, a script which is used in Hindi, a language common in India. I don't want to keep another alias picture except me or my name.

Of course. I already thought about whether it might be your name, and I'm sure that billions of people are able to read it, and I didn't want to offend you. Thank you very much for your understanding. Best regards.

**Comment by nfeske** [comment]
Hi Sagar,

welcome on board at Genodians.org! Your article just went online. Thank you for your participation!
