### ISSUE TITLE
genodians writing

### ISSUE THREAD

**Issue by gwitmond** [genodelabs/genodians.org#9]
I have my writings to offer to Genodians.org. Please use the name 'guido' for the author.
Repo: https://github.com/gwitmond/genodian

Question: does your system poll for new commits and process automatically, or do I have to ping someone when I add new article?

**Comment by nfeske** [comment]
Welcome on board Guido!

Yes, the system polls the content periodically (currently every 15 minutes, at a later stage, we may increase the interval).

To publish a new article, just push it to your github repository.

Before proceeding, please make one adjustment: The articles at genodians.org are sorted by the date of the article's file name. The dates of the articles in your genodian repository lie in the past. So by adding your repository as is, your existing articles would appear intertwined with the content already hosted at genodians.org. Let's better publish your articles individually one by one over a period of a few days or weeks so that each posting receives attention. To do so, I recommend the following procedure:

* Move your articles into a `drafts/` subdirectory. This way, genodians.org won't pick them up.
* Once you find the time is right to let one article go out into the wild, move it to the root of your genodian repository and rename it after the present date. So the posting will appear at the top spot at genodians.org.

**Comment by gwitmond** [comment]
Thanks for hosting my articles.

The 'older' articles did not have a .txt extension so they would not be published. But I like your drafts folder idea better.

**Comment by nfeske** [comment]
With commit https://github.com/genodelabs/genodians.org/commit/4b8a7c1217e985ba1ee414615790e0f7d36f7222, I added you as author.

@cnuke could you please update the system image?

@gwitmond While skimming over your article, I saw that you referrer to URLs as plain text. You may consider replacing these references by proper hyperlinks using GOSH's `[https://your.url - your title text]` markup (I think you are using this once already in the text). This way, readers can just click on the links instead of copy-pasting the URLs manually.

**Comment by cnuke** [comment]
Done.
